# CMC_download.R
# The purpose of this script is to download CMC data
# The HTTPS access for the 0.2 degree data from 1991 to 2017:
# https://podaac-tools.jpl.nasa.gov/drive/files/allData/ghrsst/data/GDS2/L4/GLOB/CMC/CMC0.2deg/v2
# The HTTPS access for the 0.1 degree data from 2016 onwards:
# https://podaac-tools.jpl.nasa.gov/drive/files/allData/ghrsst/data/GDS2/L4/GLOB/CMC/CMC0.1deg/v3
# This script should be source() run so as to be run in its entirety
# It searches first to ensure it is not downloading files that already exist
# NB: For some reason there are gaps in the daily CMC data after 2016
# This is found in both the 0.1 and 0.2 degree products


# Setup -------------------------------------------------------------------

.libPaths(c("~/R-packages", .libPaths()))
library(tidyverse)
library(tidync)
library(RCurl)
library(threadr)
library(httr)
library(lubridate)
library(doParallel); registerDoParallel(cores = 4)


# Prep --------------------------------------------------------------------

# The date ranges that are housed therein
# NB: These are historic repos and therefore the dates are static
# Links to the active portals: https://www.ghrsst.org/ghrsst-data-services/services/
date_range_old <- seq(as.Date("1991-09-01"), as.Date("2017-12-31"), by = "day")
date_range_new <- seq(as.Date("2018-01-01"), as.Date("2019-12-31"), by = "day")

# Necessary to access complete data
# NB: Note that the password credential below is not the same as the podaac login
# It is generated by the website and can be found here: https://podaac-tools.jpl.nasa.gov/drive/
user_credentials <- "robwschlegel:72cKXIj6vswyHEZ8B1D"


# Download function -------------------------------------------------------

# testers...
# date_choice <- as.Date("1991-09-02")
# date_choice <- as.Date("2017-01-01")
download_CCI <- function(date_choice, user_credentials = user_credentials){
  
  # Prep the necessary URL pieces
  date_slash <- str_replace_all(date_choice, "-", "/")
  date_nogap <- str_replace_all(date_choice, "-", "")
  date_doy <- str_pad(yday(date_choice), width = 3, pad = "0", side = "left")
  date_year <- lubridate::year(date_choice)
  front_chunk <- "https://podaac-tools.jpl.nasa.gov/drive/files/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR"
  
  if(date_choice %in% date_range_old){
    mid_chunk <- "v4.1"
    tail_chunk <- "090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc"
  } else if(date_choice %in% date_range_new){
    mid_chunk <- "v3"
    tail_chunk <- "090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc"
  } else{
    stop("The URL structure has changed.")
  }
  
  complete_URL <- paste0(front_chunk,"/",mid_chunk,"/",date_year,"/",date_doy,"/",date_nogap,tail_chunk)
  file_name <- paste0("../data/MUR/",date_nogap,tail_chunk)
  
  # Download and save the file if needed
  if(file.exists(file_name)){
    return()
  } else{
    # download_ftp_file(file_remote = complete_URL, file_local = file_name, 
    # verbose = TRUE, credentials = user_credentials)
    setwd("../data/MUR/")
    system(paste0("curl -O -u robwschlegel:fC7txB82k@jF0rVgn1V ",complete_URL))
    # download.file(url = complete_URL, method = "libcurl", destfile = file_name)
    setwd("../../tikoraluk/")
  }
  Sys.sleep(2) # Give the server a quick breather
}


# Download data -----------------------------------------------------------

# Test run
# download_CCI(date_range_old[300], base_URL_old)
# download_CCI(date_range_new[3], base_URL_new)

# Run in parallel
doParallel::registerDoParallel(cores = 4)

# Download all data from 1991 to 2016
plyr::l_ply(seq(as.Date("2016-01-21"), as.Date("2016-02-28"), by = "day"), 
            .fun = download_CCI, .parallel = T, user_credentials = user_credentials)


# Check file sizes and remove failed downloads ----------------------------

# Find files that are under a certain size
# file_sizes <- file.info(dir("../data/CMC", full.names = T)) %>%
#   mutate(file_name = row.names(.)) %>%
#   filter(size < 1500000)

# file.remove(file_sizes$file_name)

# NB: If files are removed, run the above code again


# Test visuals ------------------------------------------------------------

# test_dat <- tidync("../data/CMC/20150101120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0.nc") %>%
#   hyper_tibble()
# 
# CMC_load <- function(file_name, lon1, lon2, lat1, lat2){
#   CMC_dat <- tidync(20150101120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0.nc) %>%
#     hyper_filter(lon = between(lon, lon1, lon2),
#                  lat = between(lat, lat1, lat2)) %>% 
#     hyper_tibble() %>% 
#     select(lon, lat, time, analysed_sst) %>% 
#     dplyr::rename(t = time, temp = analysed_sst) %>% 
#     mutate(t = as.Date(t, origin = "2015-01-01"))
#   return(CMC_dat)
# }

# NB: This takes a moment to render
# ggplot(test_dat, aes(x = lon, y = lat)) +
#   geom_raster(aes(fill = analysed_sst)) +
#   borders() +
#   scale_fill_viridis_c() +
#   coord_cartesian(expand = F) +
#   theme_void()

# Extracting MUR
MUR_load <- function(file_name, lon1, lon2, lat1, lat2){
  MUR_dat <- tidync(file_name) %>%
    hyper_filter(lon = between(lon, lon1, lon2),
                 lat = between(lat, lat1, lat2)) %>% 
    hyper_tibble() %>% 
    select(lon, lat, time, analysed_sst) %>% 
    dplyr::rename(t = time, temp = analysed_sst) %>% 
    mutate(t = as.POSIXct(t, origin = "1981-01-01"))
  #mutate(t = as.POSIXct("1981-01-01 00:00:00", tz = "UTC")) 
  return(MUR_dat)
}

# Locate the files that will be loaded
MUR_files <- dir("../data/MUR_sub", full.names = T)

# Load the data in parallel
MUR_dat <- plyr::ldply(.data = MUR_files, .fun = MUR_load, .parallel = T,
                       lon1 = 11.5, lon2 = 35.5, lat1 = -38, lat2 = -24.5)

MUR_dat$Month_Yr <- format(as.Date(MUR_dat$t), "%Y-%m-%d")
MUR_dat <- MUR_dat %>% 
  select(-t)
# 123456789012345678901234567890123456789012345678901234567890123456789 
# 20150101120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0

substr(basename(ncFile), 15, 62)
fDate <- substr(basename(ncFile), 1, 8)
ncFile <- '../data/CMC/20150101120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0.nc'
test <- ymd(fDate)
nc_data <- nc_open('../data/CMC/20160203090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc')



