---
title: "Remotely SST"
author: "Amieroh Abrahams"
date: "03 August 2019"
output: html_document
---

## MUR dataset

```{r}
MUR_Lamberts_Bay <- read_csv("Data/MUR/MUR_Lamberts Bay_SST_timeseries_5nearest.csv")
MUR_Port_Nolloth <- read_csv("Data/MUR/MUR_Port Nolloth_SST_timeseries_5nearest.csv")
MUR_Saldanha_Bay <- read_csv("Data/MUR/MUR_Saldanha Bay_SST_timeseries_5nearest.csv")
MUR_Sea_Point <- read_csv("Data/MUR/MUR_Sea Point_SST_timeseries_5nearest.csv")
MUR_Hout_Bay<- read_csv("Data/MUR/MUR_Hout Bay_SST_timeseries_5nearest.csv")

MUR_SST <- rbind(MUR_Lamberts_Bay, MUR_Port_Nolloth,MUR_Saldanha_Bay, MUR_Hout_Bay, MUR_Sea_Point) %>%
  dplyr::rename(site = station)

MUR_SST$date <- (ymd(MUR_SST$date))
MUR_SST <- MUR_SST %>% 
  dplyr::rename(temp_MUR = nearest1) %>% 
  drop_na()

# save(MUR_SST, file = "Data/MUR_SST.RData")

match_func <- function(df){
  match <- SACTN_US  %>%  
  left_join(df, by = c("site", "date")) %>% 
  na.trim()
  return(match)
}

insitu_MUR <- match_func(df = MUR_SST) 
```

## CMC dataset

```{r}
Lamberts_Bay <- read_csv("Data/CMC/Lamberts Bay_SST_timeseries_5nearest.csv")
Port_Nolloth <- read_csv("Data/CMC/Port Nolloth_SST_timeseries_5nearest.csv")
Saldanha_Bay <- read_csv("Data/CMC/Saldanha Bay_SST_timeseries_5nearest.csv")
Sea_Point<- read_csv("Data/CMC/Sea Point_SST_timeseries_5nearest.csv")
Hout_Bay <- read_csv("Data/CMC/Hout Bay_SST_timeseries_5nearest.csv")

CMC <- rbind(Lamberts_Bay, Hout_Bay, Port_Nolloth, Saldanha_Bay, Sea_Point) %>%
  dplyr::rename(site = station)

CMC$date <- (ymd(CMC$date))
CMC <- CMC %>% 
  drop_na() %>% 
  dplyr::rename(temp_CMC = nearest1)

# save(CMC, file = "Data/CMC_SST.RData")

## Matching the Insitu data with the CMC SST data
insitu_CMC <- match_func(df = CMC) 
CMC_plot <- match_plot(df = insitu_CMC )
CMC_temp<- temp_plot(df = insitu_CMC)
```

## OISST

```{r}
OISSTDir <- "~/Documents/Masters_2019/Data_SST"
OISST <- fread(paste0(OISSTDir, "/csvavhrr-only-v2-19810901-20180630.csv"),
            col.names = c("lon", "lat", "temp", "date"))

# Visualise the data
# To explore the data I visualise the min temperatures along the South african coastline.

OISST %>%
  filter(date == min(date)) %>%
  ggplot(aes(x = lon, y = lat)) +
  geom_raster(aes(fill = temp))
```

## The nearest SST pixels
Now we apply the FNN (Fast Nearest Neighbor) package to determine the nearesr SST pixel to the insitu collected sites. 

```{r}

load("Data_P1/site_list_sub.Rdata") # Loading the SACTN_overlap dataset which allows me to match it to the OISST data 

unique_pixel <- OISST %>%
  select(lon, lat) %>%
  unique()

# Select nearest 1 pixels (k = 1)
# Here I use knnx to find the closes 1 pixels to the insitu sites
match_index <- knnx.index(data = as.matrix(unique_pixel[,1:2]),
                      query = as.matrix(site_list_sub[,5:6]), k = 1)

pixel_match <- unique_pixel[match_index,] %>%
  unite(col = combi, lon, lat, sep = "/", remove = F) %>%
  mutate(site = site_list_sub$site)

# Subsetting the OISST data to match the upwelling sites within the in situ collected temperature data
OISST_match <- OISST %>%
  unite(col = combi, lon, lat, sep = "/", remove = F) %>%
  filter(combi %in% pixel_match$combi)
# save(OISST_match, file = "Data_P1/OISST_match.RData")

OISST_sites <- OISST_match %>%
  left_join(pixel_match, by = c("combi", "lon", "lat")) %>%
  dplyr::rename(temp_OISST =temp)

OISST_sites <- OISST_sites %>% 
  dplyr::rename(temp = temp_OISST) %>%
  dplyr::mutate(date = as.Date(date)) %>% 
  drop_na()
# save(OISST_sites, file = "Data_P1/OISST_sites.RData")

## Matching the Insitu data with the OISST SST data
insitu_OISST <- match_func(df = OISST_sites)
```





