---
title: "Abstract"
author: "Amieroh Abrahams"
date: "18 September 2019"
output: html_document
---

## Abstract
Abstract

The South African coastline is comprised of three distinct coastal regions, each varying in average temperaturedue to the presence of two distinct ocean currents; namely the Agulhas and Benguela currents, an eastern boundry upwelling system (EBUS). This study was designed to see if the same upwelling patterns are visible at different distances from the coastline and in diffeent datasets. Analyses of temperature time series data from 4 sites within the west coast of South Africa were conducted to examine variation in intensity occuring at different upwelling events at different distances from the coastline. This study futher made use of wind data to determine the upwelling index for each of the sites. By using the ANOVA analyses, it was possible to determine the relationship between intensity for each of the sites at variable distnces. Results showed high intensity of upwelling events in the OISST dataset but less high intensities in the CMC dataset. Similar upwelling patterns are present in the in situ and OISST dataset at a distace of 10km from the coastline. At a distance of 50km from the coastline less upwelling events are detected in both remotely sensed datasets.
