---
title: "Paper 2"
author: "Amieroh Abrahams"
date: "16 September 2019"
output: html_document
---

## Introduction to paper 2: INcrease in intensity and duration of upwelling events








### Last paragraph in paper 2 introduction ###
Global warming is increasing at an extremely high rate. This will result in an increase in greenhouse gases which in turn will impact the ocean and terrestrial life. The process of upwelling is one such factor that is predicted to change with an increase in global warming. As previously mentioned, changes in temperature results in changes in pressure gradients, these pressure gradients control wind patterns which ultimately controls the intensity and duration of upwelling. To assess the changes within the upwelling events, various datasets would be used. These are satellite sea surface temperatures (broad scale), in situ collected seawater temperatures (local scale), wind data as well as satellite obtained chlorophyll-a data. Having assessed the eastern boundry upwelling system within a context that comprised of broad and local-scale features permitted us to assess how upwelling varied between sites located closer to the upwelling centres and furthur away from the upwelling centre. Specifically, we aim to assess whether or not it is possible to identify the upwelling signal throughout the various datasets and here we examine how far offshore the upwelling signal is present in the higher resolution data and how far offshore the SACTN signal extend. We hypothesized that (i) wind action may influence the intensity and duration of upwelling; (ii) Remotely sensed SST data will represent a similar event frequency and duration; (iii) Sites located closer to upwelling centres displays distinct variation in the intensity and duration of upwelling events compared to sites furthur away from the upwelling centeres.